version: '3.8'

services:
  db:
    container_name: pg_db
    image: postgres:alpine3.18
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db_account
    command:
      - "postgres"
      - "-c"
      - "port=5435"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5435:5435"

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: PGadmin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: PGadmin
    ports:
      - "5050:80"